# Generated by Django 3.0.4 on 2020-03-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createcontest', '0003_auto_20200331_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='createcontest',
            name='problem_memory_limit_1',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='createcontest',
            name='problem_memory_limit_2',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='createcontest',
            name='problem_memory_limit_3',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='createcontest',
            name='problem_memory_limit_4',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='createcontest',
            name='problem_memory_limit_5',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='createcontest',
            name='problem_time_limit_1',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='createcontest',
            name='problem_time_limit_2',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='createcontest',
            name='problem_time_limit_3',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='createcontest',
            name='problem_time_limit_4',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='createcontest',
            name='problem_time_limit_5',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
