# Generated by Django 3.0.4 on 2020-04-09 16:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createcontest', '0005_auto_20200401_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createcontest',
            name='problem_description_1',
            field=ckeditor.fields.RichTextField(default='-'),
        ),
    ]
