# Generated by Django 3.0.4 on 2020-04-09 22:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createcontest', '0006_auto_20200409_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createcontest',
            name='problem_description_2',
            field=ckeditor.fields.RichTextField(default='-'),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_description_3',
            field=ckeditor.fields.RichTextField(default='-'),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_description_4',
            field=ckeditor.fields.RichTextField(default='-'),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_description_5',
            field=ckeditor.fields.RichTextField(default='-'),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_input_1',
            field=ckeditor.fields.RichTextField(default='-'),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_input_2',
            field=ckeditor.fields.RichTextField(default='-'),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_input_3',
            field=ckeditor.fields.RichTextField(default='-'),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_input_4',
            field=ckeditor.fields.RichTextField(default='-'),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_input_5',
            field=ckeditor.fields.RichTextField(default='-'),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_note_1',
            field=ckeditor.fields.RichTextField(default=' '),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_note_2',
            field=ckeditor.fields.RichTextField(default=' '),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_note_3',
            field=ckeditor.fields.RichTextField(default=' '),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_note_4',
            field=ckeditor.fields.RichTextField(default=' '),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_note_5',
            field=ckeditor.fields.RichTextField(default=' '),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_output_1',
            field=ckeditor.fields.RichTextField(default='-'),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_output_2',
            field=ckeditor.fields.RichTextField(default='-'),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_output_3',
            field=ckeditor.fields.RichTextField(default='-'),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_output_4',
            field=ckeditor.fields.RichTextField(default='-'),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_output_5',
            field=ckeditor.fields.RichTextField(default='-'),
        ),
    ]
