# Generated by Django 3.0.4 on 2020-04-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createcontest', '0007_auto_20200409_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='createcontest',
            name='contest_setter',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
