# Generated by Django 3.0.4 on 2020-04-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createcontest', '0008_createcontest_contest_setter'),
    ]

    operations = [
        migrations.AddField(
            model_name='createcontest',
            name='contest_time',
            field=models.DateTimeField(null=True),
        ),
    ]
