# Generated by Django 3.0.4 on 2020-04-17 23:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createcontest', '0009_createcontest_contest_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createcontest',
            name='contest_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='contest_setter',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_description_1',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_description_2',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_description_3',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_description_4',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_description_5',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_input_1',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_input_2',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_input_3',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_input_4',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_input_5',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_memory_limit_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_memory_limit_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_memory_limit_3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_memory_limit_4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_memory_limit_5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_name_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_name_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_name_3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_name_4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_name_5',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_note_1',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_note_2',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_note_3',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_note_4',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_note_5',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_output_1',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_output_2',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_output_3',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_output_4',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_output_5',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_time_limit_1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_time_limit_2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_time_limit_3',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_time_limit_4',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_time_limit_5',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
