# Generated by Django 3.0.6 on 2020-06-01 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createcontest', '0010_auto_20200417_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createcontest',
            name='contest_time',
            field=models.DateTimeField(default=datetime.date.today, null=True),
        ),
    ]
