# Generated by Django 3.0.6 on 2020-06-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createcontest', '0011_auto_20200601_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='createcontest',
            name='problem_picurl_1',
            field=models.TextField(default='-'),
        ),
    ]
