# Generated by Django 3.0.6 on 2020-06-11 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createcontest', '0012_createcontest_problem_picurl_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='createcontest',
            name='problem_pic_name_1',
            field=models.TextField(null=True),
        ),
    ]
