# Generated by Django 3.0.6 on 2020-06-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createcontest', '0016_auto_20200612_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createcontest',
            name='problem_pic_url_1',
            field=models.TextField(default='-'),
        ),
    ]
