# Generated by Django 3.0.7 on 2020-06-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createcontest', '0017_auto_20200612_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createcontest',
            name='problem_description_1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_description_2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_description_3',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_description_4',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_description_5',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_input_1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_input_2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_input_3',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_input_4',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_input_5',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_note_1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_note_2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_note_3',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_note_4',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_note_5',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_output_1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_output_2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_output_3',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_output_4',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='createcontest',
            name='problem_output_5',
            field=models.TextField(null=True),
        ),
    ]
